---
# Ansible role
#
# Konfigurace OpenLDAP TLS

- name: Příprava LDIF TLS
  template:
    src: 'ldap-tls.ldif.j2'
    dest: '/etc/ldap/{{ openldap.organization }}/ldap-tls.ldif'
    force: false
  register: openldap_activate_tls

- name: Aktivace TLS
  block:
    - name: Restart slapd poprvé
      service:
        name: 'slapd'
        state: restarted

    - name: Import LDIF with TLS config
      command: >-
        ldapmodify
          -Y EXTERNAL
          -H ldapi:///
          -f /etc/ldap/{{ openldap.organization }}/ldap-tls.ldif

    - name: Restart slapd podruhé
      service:
        name: 'slapd'
        state: restarted

  when: openldap_activate_tls is changed

- name: Vynucení TLS pro každé spojení
  ldap_attr:
    dn: 'olcDatabase={1}mdb,cn=config'
    name: 'olcSecurity'
    values: 'tls=1'
    state: "{{ 'exact' if openldap.tls.force else 'absent' }}"
  notify: Restart slapd

- name: Vynucení TLS 1.2
  ldap_attr:
    dn: 'cn=config'
    name: 'olcTLSProtocolMin'
    values: '3.3'
    state: exact
  notify: Restart slapd

- name: Nastaví typy TLS šifer
  ldap_attr:
    dn: 'cn=config'
    name: 'olcTLSCipherSuite'
    values: '{{ openldap.tls.priority_string }}'
    state: exact
  notify: Restart slapd

- name: Zapnutí ldaps
  lineinfile:
    path: '/etc/default/slapd'
    line: "SLAPD_SERVICES=\"ldap:/// ldapi:///{{ ' ldaps:///' if openldap.tls.ldaps else '' }}\""
    regexp: '^SLAPD_SERVICES'
  notify: Restart slapd

...
